### ISSUE TITLE
Issue with PhD thesis format

### ISSUE THREAD

**Issue by santhu37** [Bama-S/auugthesisformat#1]
Dear Madam,
                       I'm preparing my PhD thesis with the template from CFR website. The 'auapalike.bst' file is missing in that template. After a day searching for solutions, i found it in the UG thesis format. I would like to know whether i can use the same file for PhD thesis? 
                      I have one more query regarding preparation of 'references.bbl' file. I'm used to creation of citations with '.bib' file and not aware of '.bbl' formats. I would be glad to know any resource that could help me to handle it.
                      I'm not aware of any common discussion forum for helping PhD students in latex thesis preparation. If  there is a forum, please do let me know. I have started one here.

https://goo.gl/x9cCKa

**Comment by Bama-S** [comment]
Can you please send your email address. And please mention your name and
affliation. My email address is chorse@gmail.com, bama@annauniv.edu. At
present, because of Chennai rains, Anna University servers may be down. So,
please address to gmail account.

Regarding bst, I don't think there is any change. But will check and let
you know.

Regards
-Bama

**Comment by santhu37** [comment]
Respected Madam,
                                I must thank you for the kind reply. I'm santhosh, doing full-time PhD in EEE department at Government College of Engineering, Salem. I've begun to prepare my thesis with LaTeX format available in CFR website. I've had several issues and resolved them all. 
                             Currently, I'm having a specific issue with the bibliography. The references format returned by 'auapalke' bibliography style is producing 'and' between author names instead of '&' in the generated output. I'm using a '.bib' database for storing references exported from Mendeley software. I'm not aware of any feasible solution. I would be happy if you could help me in this issue.
                                My mail-id is 'tksanthosh.kct@gmail.com' and i'm looking for your kind support. Thank you once again.

**Comment by santhu37** [comment]
I forgot to mention that I have sent a reply mail as soon as i got yours and I'm not sure whether it reached you. I'm writing this mail seeking your kind help and support.

**Comment by Bama-S** [comment]
I'm seeing your mail just now. I'll check up tomorrow and will inform you.

--Bama

On Dec 19, 2015 9:09 PM, "santhu37" <notifications@github.com> wrote:
>
> I forgot to mention that I have sent a reply mail as soon as i got yours
and I'm not sure whether it reached you. I'm writing this mail seeking your
kind help and support.
